# Generated by Django 4.1.3 on 2022-12-04 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Queries",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("type", models.CharField(max_length=50)),
                ("topic", models.CharField(max_length=50)),
                ("description", models.CharField(max_length=250)),
                ("query", models.CharField(max_length=5000)),
            ],
            options={
                "ordering": ["topic"],
            },
        ),
    ]
